/* Generated by Together */

package framework.mentalState.belief;

import java.io.Serializable;

/**
 * Responsável por representar as características estruturais e comportamentais
 * de uma crença simples.  
 */
public class LeafBelief extends Belief implements Serializable 
{
	/**
	 * Construtor da classe responsável por atribuir o tipo, o nome e o objeto
	 * associado à crença simples.
	 * 
	 * @param type
	 * Tipo da crença simples.
	 * @param name
	 * Nome da crença simples.
	 * @param value
	 * Objeto associado à crença simples.
	 */
    public LeafBelief (String type, String name, Object value)
    {
        this.type = type;
        this.name = name;
        this.value = value;
    }
}
